//package com.golden.gui;
//
//import com.golden.metier.AuthentifMetier;
//import java.sql.SQLException;
//import javax.swing.JOptionPane;
//
///**
// *
// * @author Mohamed
// */
//public class AuthentifGui extends javax.swing.JFrame {
//
//    /** Creates new form AuthentifGui */
//    public AuthentifGui() {
//        initComponents();
//    }
//
//    /** This method is called from within the constructor to
//     * initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is
//     * always regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        jLabel2 = new javax.swing.JLabel();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        txtLogin1 = new javax.swing.JTextField();
//        btnConnexion = new javax.swing.JButton();
//        txtPassword = new javax.swing.JPasswordField();
//
//        jLabel2.setText("jLabel2");
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setTitle("Accès My Garde-Robe");
//
//        jLabel1.setText("Login");
//
//        jLabel3.setText("Password");
//
//        txtLogin1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtLogin1ActionPerformed(evt);
//            }
//        });
//
//        btnConnexion.setText("Connexion");
//        btnConnexion.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnConnexionActionPerformed(evt);
//            }
//        });
//
//        txtPassword.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtPasswordActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(65, 65, 65)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jLabel3)
//                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(71, 71, 71)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                            .addComponent(txtPassword)
//                            .addComponent(txtLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(151, 151, 151)
//                        .addComponent(btnConnexion)))
//                .addContainerGap(91, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(37, 37, 37)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addComponent(jLabel1)
//                    .addComponent(txtLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(18, 18, 18)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel3)
//                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(74, 74, 74)
//                .addComponent(btnConnexion)
//                .addContainerGap(102, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>                        
//
//    private void txtLogin1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        // TODO add your handling code here:
//    }                                         
//
//    private void btnConnexionActionPerformed(java.awt.event.ActionEvent evt) {                                             
//     AuthentifMetier userM=new AuthentifMetier();
//        try {
//            boolean verif=userM.verifyAccess(txtLogin1.getText(),
//                    new String(txtPassword.getPassword()));
//            if(verif==true){
////            Acceuil acc=new Acceuil();
////            acc.setVisible(true);  //baguette magique
////            this.setVisible(false);
//                JOptionPane.
//           showMessageDialog(this, "Connexion etablie avec succes");
//                    }
//            else
//                JOptionPane.
//           showMessageDialog(this, "login &/ou password erroné!!!");
//            txtLogin1.setText("");
//            txtPassword.setText("");
//
//
//        } catch (SQLException ex) {
//            System.out.println(ex.getMessage());     }
//        catch (ClassNotFoundException ex) {
//        System.err.println("Driver not found "+ex.getMessage());
//        }
//
//    }                                            
//
//    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        // TODO add your handling code here:
//    }                                           
//
//    /**
//    * @param args the command line arguments
//    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AuthentifGui().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify                     
//    private javax.swing.JButton btnConnexion;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JTextField txtLogin1;
//    private javax.swing.JPasswordField txtPassword;
//    // End of variables declaration                   
//
//}
